version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://${NONGO_PRICECOMPARE_USERNAME}:${NONGO_PRICECOMPARE_PASSWORD}@mongo:27017/price-compare # Connect to MongoDB container ${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@
    ports:
      - "3000:3000"
      - "5900:5900"
      - "6080:6080"
  mongo:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  frontend:
    build:
      context: ./src/web/my-app
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    restart: always    # Add this line
    healthcheck:      # Add this health check
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - app

volumes:
  mongo-data:
